### ISSUE TITLE
Warning: extract() expects parameter 1 to be array

### ISSUE THREAD

**Issue by teod** [apsislabs/cf7-gated-content#1]
We are receiving this error on our wordpress website when using the plugin:
`Warning: extract() expects parameter 1 to be array, string given in /home/smartup3/public_html/wp-content/plugins/cf7-gated-content/cf7_gated_content.php on line 209`

**Comment by ncallaway** [comment]
That you for the report.

We've got a busy morning, so I'll try and look into this issue this afternoon. If I need any more information I'll let you know.

Thanks

**Comment by ncallaway** [comment]
Quick update on this issue: we were able to reproduce it on our end, and have a potential fix. It's out as a pull request now, and should be merged in sometime in the next day or so.

I'll let you know when the fix is merged into the branch, and again when the fix is published to the wordpress plugin repository.

**Comment by ncallaway** [comment]
This fix has been merged into `master`. I'll let you know when we've pushed the fix to the plugin repository.

**Comment by wkirby** [comment]
@teod This should now be deployed and available to update through the plugin repository.
