### ISSUE TITLE
Gated content download button not showing (same as issue 16)

### ISSUE THREAD

**Issue by batmush** [apsislabs/cf7-gated-content#17]
Hi,
The issue 16 is closed but not resolved.
I installed your new plugin but you disappeared and don't respond my emails.

**Comment by wkirby** [comment]
@batmush first of all this is free, open-source software. The maintainers have full-time jobs that don't include fixing your site. Second, as mentioned in our emails: all indications are that this plugin is working correctly — the expected cookies are being set, and the plugin is neither logging nor throwing any errors.

What I _can_ say is happening is that something else is wrong with your CF7 setup. The most obvious indicator is that the CF7 AJAX submission is not working — CF7 only falls back to standard form submission if there is a problem with submitting via AJAX. The second indication that something is wrong is that when the form is submitted, the success message is _also_ broken (![screenshot here](https://user-images.githubusercontent.com/579688/88074068-f19c7a00-cb44-11ea-926e-9f2ec1fc8f3d.png)).

My recommendation is the same as it was previously: disable plugins and your theme until you identify which one is causing the problem. Locally I have installed all the same plugins as you, and the form works as expected (
![see video](https://user-images.githubusercontent.com/579688/88076171-be0f1f00-cb47-11ea-9dbe-120034161276.gif)
), so the most likely culprit is your Wordpress theme.

I'm going to close this issue because, until you can demonstrate that there's actually a problem with this plugin rather than with your site, there's nothing our devs are going to be able to do about it. In the future, I'd think about how politely you interact with people who give their time to help you.
