### ISSUE TITLE
Form not including the download

### ISSUE THREAD

**Issue by loudertd** [apsislabs/cf7-gated-content#18]
When I try to create the form in Contact Form 7 one of two things happen when I enable the gated content: 

1. The "Download"button is the only thing that appears, the form doesn't show up.

2. The form shows up, but there is no download button for the gated content. 

Images attached of my current set up. 
![Screen Shot 2020-10-15 at 11 54 17 AM](https://user-images.githubusercontent.com/72937992/96161750-4a2daa00-0edd-11eb-884e-c8c7b40639d4.png)
![Screen Shot 2020-10-15 at 11 54 27 AM](https://user-images.githubusercontent.com/72937992/96161753-4ac64080-0edd-11eb-8cef-5bc81aef7fa3.png)
![Screen Shot 2020-10-15 at 11 54 36 AM](https://user-images.githubusercontent.com/72937992/96161754-4b5ed700-0edd-11eb-91e7-0da583169e45.png)

**Comment by wkirby** [comment]
Hi @loudertd — what you're describing is the expected behavior. Once the form is submitted (and valid), the form content is hidden and the download button appears. This will set a cookie that will skip the form on future visits. If you'd like the visitor to _always_ fill out the form, regardless of past submissions, you can check the `Always Require Form` option on the settings page.

**Comment by wkirby** [comment]
Closing as stale
