### ISSUE TITLE
Autoscroll on submit

### ISSUE THREAD

**Issue by inaiontcheva** [apsislabs/cf7-gated-content#20]
After submitting the form, there is an automatic scroll to the bottom of the page. How can this action be removed? I can’t find an option in the plug-in settings. Should some custom JavaScript code be added?

**Comment by wkirby** [comment]
Hi @pipiparaguas, thanks for the report. I'm not aware of any code in our codebase that would cause the scroll after submit — can you confirm that this behavior is because of CF7 gated content? Does it happen if the gated content plugin is disabled?

Also, if possible, please provide a a link to where I can test the form.

**Comment by wkirby** [comment]
Closing as stale
