### ISSUE TITLE
Download button still showing on Submit with no gated content

### ISSUE THREAD

**Issue by NPC** [apsislabs/cf7-gated-content#6]
Hi, this seems like a duplicate for #3, my form page is https://iplanworld.com/contact/ (you can send a test message if it helps, just say that it's a test). For now I've hidden the Download button with CSS as I can find no other way.

WP version: 5.2.2
Plugin version: 1.3.1

Config screenshot (no gated content that I can see):
![image](https://user-images.githubusercontent.com/564364/60205721-cd1d8380-9806-11e9-8036-d9177b622cd7.png)

**Comment by wkirby** [comment]
Hi @NPC, thanks for the report. Is the issue here that:

1. You are seeing the download button appear on submission, even if there are form errors (this is the bug reported in #3)
2. You are seeing the download button appear on forms even when you have not set any gated content (this is what appears to be the issue in your screenshot)

Thanks!

**Comment by NPC** [comment]
Ah, sorry, I guess I didn't read #3 attentively enough. 

I have issue 2, there's no gated content (it's just a contact form), but Download button still appears after submitting the form.

**Comment by wkirby** [comment]
@NPC No problem. I see exactly the issue here. I will do my best to have an update for this out by the end of the week.

**Comment by wkirby** [comment]
@NPC Sorry this took way too long to get to. We've released `1.4.0` which fixes this issue.

**Comment by NPC** [comment]
@wkirby No worries and thanks for the fix. I'll be able to test it on Wednesday, I'll let you know if there are any issues.

**Comment by NPC** [comment]
@wkirby Everything looks good, thanks again for fixing this!
